### ISSUE TITLE
Image scaling off on single posts and grid

### ISSUE THREAD

**Issue by simplemama** [bearded-avenger/aesop-core#141]
Featured images are not scaling properly on mobile devices for:

 * grid homepage items (Novella, Kerouac, and Jorgen)
 * main featured image at the top of each post

Instead of scaling, the images are being cropped.

Reference with screenshots: http://aesopstoryengine.com/topic/responsiveness-iphone/

**Comment by peiche** [comment]
Can this be closed? It seems to me this is a theme-specific issue.

**Comment by michaelbeil** [comment]
Yes.
