### ISSUE TITLE
ASE 1.4 and http://data.fotorama.io

### ISSUE THREAD

**Issue by AlchemyUnited** [bearded-avenger/aesop-core#193]
Hey guys

fyi - this is still showing in 1.4. I even deleted via Admin CP and then reinstalled. Still, it's there. 

    <iframe src="http://data.fotorama.io/?version=4.6.2" style="display: none;"></iframe>

**Comment by michaelbeil** [comment]
We should have a new release coming out to clear this miscreant later this week.

**Comment by bearded-avenger** [comment]
TBH I'm not sure how it's still in there with window.fotoramaBlock. At any rate, they removed it upstream finally, and we removed it completely out of core instead of just blocking it. 
https://github.com/artpolikarpov/fotorama/issues/299

**Comment by AlchemyUnited** [comment]
Thanks guys. I'm sure it's some bullshit. And...bullshit - like the WYSIWYG - be gone :)

**Comment by michaelbeil** [comment]
If you want to fix this on your current install straight away, you could pull from this branch: https://github.com/bearded-avenger/aesop-core/tree/release/1.4.1

**Comment by AlchemyUnited** [comment]
Mo biggie @michaelbeil . Client / project isn't live yet. We can wait for the next great ship.
