### ISSUE TITLE
AESOP is blocking other TinyMCE plugins

### ISSUE THREAD

**Issue by SebaSOFT** [bearded-avenger/aesop-core#194]
If a TinyMCE plugin is registered before the "aiview" and "noneditable", then they are lost because AESOP is not adding to the plugins array in the file class-aesop-core-admin.php line: 167

Tested with AESOP 1.2

**Comment by bearded-avenger** [comment]
Does this happen with the current version, 1.4.1 ? Also, do you have an example plugin that's loading  it's own TinyMCE plugin?

**Comment by SebaSOFT** [comment]
Already made a Pull request.

https://github.com/bearded-avenger/aesop-core/pull/195

**Comment by bearded-avenger** [comment]
Ahh completely missed this. thanks for catching that!

**Comment by SebaSOFT** [comment]
Not a problem

**Comment by michaelbeil** [comment]
That was fast!

**Comment by bearded-avenger** [comment]
move fast and break shit

**Comment by michaelbeil** [comment]
Break ALL the shiste.
