### ISSUE TITLE
[Firefox] Edited component move to the top of the editor

### ISSUE THREAD

**Issue by jchatard** [bearded-avenger/aesop-core#202]
Hi, first, great module!

Under Firefox (tested on Chrome and Safari), when a component (at least image) is edited, from the WYSIWYG, it is moved to the top of the editor, becoming the first "markup of the content" zone.

![screen_shot_2015-02-14_at_18_15_51](https://cloud.githubusercontent.com/assets/6790/6200380/bceced6c-b475-11e4-8000-ddefe2553ed9.jpg)

This is pretty annoying :-)

**Comment by bearded-avenger** [comment]
I'm not able to replicate this at all. Are you able to do it every time? Any JS errors?

**Comment by jchatard** [comment]
Hmm, no JS error, just this warning, but I guess it's common on all browser anyway:

`Deprecated TinyMCE API call: <target>.onClick.add(..)`

Just in case, I'm using Novella...

**Comment by jchatard** [comment]
And it's the same with the parallax component. I'll try some others just to check, I'm using Firefox 35.0.1 on OS X.

**Comment by jchatard** [comment]
Ah, ah, yeah on all :-)

As you can see, my Wordpress is in French, but it would unlikely that this is related... I guess.

![screen shot 2015-02-14 at 18 30 12](https://cloud.githubusercontent.com/assets/6790/6200420/922b0044-b477-11e4-9acc-6a6c39c8656b.png)

**Comment by michaelbeil** [comment]
I can replicate this too. We are checking into it.

**Comment by jchatard** [comment]
Ok, great!

**Comment by michaelbeil** [comment]
For now you could just use Chrome or Safari.

**Comment by jchatard** [comment]
Yeah, yeah sure! No worries, no rush :+1:

**Comment by etcook** [comment]
Unfortunately, the bubbling behavior didn't work properly with the other TinyMCE API. You don't need to use another browser. If you don't want to see it until an alternative can be found, turn off your dev tools.

**Comment by bearded-avenger** [comment]
thanks @jchatard we'll look into it!
