### ISSUE TITLE
Chapter navigation is missing a wrapper

### ISSUE THREAD

**Issue by garand** [bearded-avenger/aesop-core#203]
I noticed that the timeline and chapter navigation components use the same markup, but the timeline navigation includes a wrapper around it for styling, whereas the chapter navigation does not, which doesn't allow me to style the chapter navigation independently.

**Comment by michaelbeil** [comment]
You could filter it (docs here: http://aesopstoryengine.com/developers), using the `aesop_COMPONENTNAME_component_classes` filter. 

This filter can add custom CSS classes to any component. Here’s an example of how to add two classes, red and blue, to the chapter component.

```
add_filter("aesop_chapter_component_classes","myaddclasses");
function myaddclasses(){
return "red blue";
}
```

**Comment by bearded-avenger** [comment]
Chapter menu has plenty of wrappers
http://cl.ly/image/0t0e1R0e1M26

**Comment by garand** [comment]
@bearded-avenger Hmm... I'm not seeing that. Let me see if there is something else overriding that somehow or if I'm not using the latest version. I'll follow up later.

**Comment by bearded-avenger** [comment]
Yeah I think we made this stuff automatic back in 1.3.2. It adds a #aesop-chapter-menu div who's markup is also filterable. https://github.com/bearded-avenger/aesop-core/blob/master/public/includes/components/component-heading.php#L164

**Comment by chriswallace** [comment]
I HAVE AN IDEA MORE DIVS

**Comment by bearded-avenger** [comment]
LOL this guy

**Comment by garand** [comment]
😐
