### ISSUE TITLE
Parallax 'no movement' bug

### ISSUE THREAD

**Issue by michaelbeil** [bearded-avenger/aesop-core#232]
There is a bug with the Parallax component when movement is turned off. Height of image is ignored.
http://cl.ly/image/471l0B2O1I0K

See: http://aesopstoryengine.com/topic/ase-parallax-no-movement-problem/#post-7621

**Comment by bearded-avenger** [comment]
fixed with https://github.com/bearded-avenger/aesop-core/commit/025ae9b
