### ISSUE TITLE
Fitvid not calculating video size properly

### ISSUE THREAD

**Issue by dryanmedia** [bearded-avenger/aesop-core#248]
Fitvid is inserting improper padding =\

A value of ```padding-top: 50%;``` is added to each fitvid'd video, no matter the vendor, resulting in black canvas in the video player.

**YouTube** (proper ratios: with controls: 60.75%, without controls 56.25%)
Aesop displays:
![screen shot 2015-04-21 at 11 22 59 am](https://cloud.githubusercontent.com/assets/9565066/7259696/0211604e-e81a-11e4-93fa-58cf768aa0f7.png)

**Vimeo** (proper ratio 56.25%)
Aesop displays:
![screen shot 2015-04-21 at 11 24 36 am](https://cloud.githubusercontent.com/assets/9565066/7259781/a5751ea6-e81a-11e4-8fa3-286e4b794f00.png)

Is there specific reason for using javascript instead of using straight css? 
Seems simpler to do vendor-specific css and remove reliance on JavaScript?

Users accept bars on 4:3 video now, but particularly for fullscreen embeds edge-to-edge fill and proper sizing for 16:9 videos is important.

**Comment by bearded-avenger** [comment]
CSS method isn't reliable, FitVids is. 

They account for multiple vendors. https://github.com/davatron5000/FitVids.js/blob/master/jquery.fitvids.js#L36

It could be Aesop CSS itself?

**Comment by bearded-avenger** [comment]
Use vidwidth and vidheight attributes. These do not show in the UI.

https://github.com/bearded-avenger/aesop-core/blob/master/public/includes/components/component-video.php#L26

**Comment by dryanmedia** [comment]
@bearded-avenger Don't think it's Aesop CSS. Padding is added inline -- line 51 in [fit-vids.js](https://github.com/bearded-avenger/aesop-core/blob/master/public/assets/js/fit-vids.js).

Tried using vidwidth and vidheight, but no change. Tried including measurements with proper ratio too.
```[aesop_video width="100%" align="center" src="vimeo" id="87701971" loop="on" autoplay="on" controls="on" viewstart="on" viewend="on" vidwidth="580" vidheight="281"]```

![screen shot 2015-04-21 at 12 07 18 pm](https://cloud.githubusercontent.com/assets/9565066/7260478/06fb9340-e81f-11e4-91c9-495b6cca628f.png)

**Comment by dryanmedia** [comment]
@bearded-avenger any thoughts on the **vidwidth** and **vidheight** not accepting values? They don't seem to be passing to front-end at all =| No matter what black bars appear, issue persists.

I'm going to keep toying, but any thoughts appreciated.

**Comment by bearded-avenger** [comment]
I'll dive in and take a look today
