### ISSUE TITLE
Fix Unnecessarily Slow Query

### ISSUE THREAD

**Issue by bearded-avenger** [bearded-avenger/aesop-core#254]
/admin/includes/components/component-map.php

aesop_check_for_old_markers()

we're literally pulling every post for marker checks on an upgrade routine :(

**Comment by bearded-avenger** [comment]
fixed with https://github.com/bearded-avenger/aesop-core/commit/dfc3aae2423836cc43b75c516911c63f3a4ead53

**Comment by michaelbeil** [comment]
I don't know how we missed this. So glad it was found.
