### ISSUE TITLE
Editing a previously placed Content component strips out image tags

### ISSUE THREAD

**Issue by michaelbeil** [bearded-avenger/aesop-core#260]
Floater Element Content field gets partially stripped out.

The original content of the field was this:
`<img src="IMAGE_URL" />`

When a user goes in to edit that component, the field contains just this:
`<img sr`

However, the full HTML is still in the text editor.

ref: http://aesopstoryengine.com/topic/editing-a-previously-placed-content-component-strips-out-image-tags

**Comment by bearded-avenger** [comment]
yeah this is due to the media filter that we have. security against carnies. you know, circus folk.
![carnie-2](https://cloud.githubusercontent.com/assets/1317303/7850204/7f539ea4-04a4-11e5-9c26-fe0b2200a0c3.jpg)

**Comment by bearded-avenger** [comment]
This isn't a bug actually, it's because its a shortcode attribute. enter image urls without quotes around the source

**Comment by michaelbeil** [comment]
Got it.
