### ISSUE TITLE
Can't expand or collapse in dashboard

### ISSUE THREAD

**Issue by faoliveira** [bearded-avenger/aesop-core#274]
Hi!

I can't expand or collapse in dashboard while I'm editing a post, neither drag and drop. When I disable the Aesop back to normal. Chrome console points to this error:

    Uncaught TypeError: Cannot read property 'hasClass' of undefined!

Source code in dashboard: http://pastebin.com/ND28eFNK
Chrome Console: 
![chrome-console](https://cloud.githubusercontent.com/assets/1172634/8897587/3ae371e4-33ee-11e5-8020-dce17c67a7a3.jpg)

Wordpress 4.2.3
AESOP 1.6.3
Using [Bedrock](https://github.com/roots/bedrock). Folder structure:
📂 app
└📁 plugins
    └📁 aesop-story-engine

Any additional information, just ask :) Thanks for the plugin!

**Comment by bearded-avenger** [comment]
I use bedrock on several setups, is there any reason why Aesop Story Engine isn't in app/plugins ?

**Comment by bearded-avenger** [comment]
Not that it should matter, but I've just never run across this issue, nor has it been reported before.

**Comment by faoliveira** [comment]
Oh sorry, it's in app/plugins. My mistake. For some reason, after reinstall (again) Wordpress today, back to normal

**Comment by michaelbeil** [comment]
Glad to hear all is well. Cheers on your day!
