### ISSUE TITLE
Timeline issue showing up

### ISSUE THREAD

**Issue by michaelbeil** [bearded-avenger/aesop-core#284]
ASE 1.6.4 seems to have broken the timeline component.

Tracing down the culprit.

**Comment by bearded-avenger** [comment]
Yep this was a byproduct of the shortcode fix from #279. Fixed!

**Comment by michaelbeil** [comment]
Sweetness!

**Comment by michaelbeil** [comment]
Shall we PR, merge, and SVN?

**Comment by michaelbeil** [comment]
Fixed in #286.
