### ISSUE TITLE
Can't remove the map component from all pages

### ISSUE THREAD

**Issue by ogdsgn** [bearded-avenger/aesop-core#291]
Hey there, great plugin by the way!

I'm trying to remove the map component from my pages as I'm already using another map solution. I was able to use the following filter to remove the shortcode, and that also removes the component from the 'add component' dropdown, but the filter for removing the meta box from the posts&pages doesn't seem to work.

This is the snippet I am using to filter the meta.
apply_filters('aesop_map_meta_location', array( '' ) );

I was able to disable the map component completely by commenting out the following line in the core-admin.php, but obviously I don't want to be doing that (just need to remove it for the time being until I can accomplish it in my theme.

require_once AI_CORE_DIR . 'admin/includes/components/component-map.php';

thanks!

**Comment by michaelbeil** [comment]
You can uncheck the map component box from within the options panel located at the top right of the post editor. If you trigger that to be unchecked all should work fine.

Does that help?

**Comment by ogdsgn** [comment]
Perfect. Found it!

**Comment by michaelbeil** [comment]
Glad to hear @ogdsgn!
