### ISSUE TITLE
Missing Images cause an error on FrontEnd

### ISSUE THREAD

**Issue by ogdsgn** [bearded-avenger/aesop-core#295]
I ran into an issue where I have an image gallery component and it's referencing an image that no longer exists in the media gallery.

This is the error I get on the front end.
Trying to get property of non-object in Notice: Trying to get property of non-object in aesop-story-engine/public/includes/components/component-gallery.php on line 376

Would it be easy enough to create a default fallback image so this could fail gracefully?

Thanks in advance!

**Comment by michaelbeil** [comment]
Please direct this to our support forums as this repository is for tracking bugs and feature requests once we know what the issue is: https://wordpress.org/support/plugin/aesop-story-engine.

**Comment by ogdsgn** [comment]
oh sorry michael.

cheers.
